CREATE TABLE IF NOT EXISTS definitions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lang VARCHAR(10) NOT NULL,
    src VARCHAR(255) NOT NULL,
    word VARCHAR(100) NOT NULL,
    def TEXT NOT NULL
);